### PR TITLE
add support for angular 17+ with no error in peer deps

### LINKED ISSUE #98: Incompatible with Angular 17
`npm ERR! Found: @angular/common@17.0.8

npm ERR! node_modules/@angular/common

npm ERR!   @angular/common@"^17.0.2" from the root project

npm ERR! 

npm ERR! Could not resolve dependency:

npm ERR! peer @angular/common@"^16.0.0" from ng-svg-icon-sprite@1.13.2

npm ERR! node_modules/ng-svg-icon-sprite

npm ERR!   ng-svg-icon-sprite@"1.13.2" from the root project
`

### PR DESCRIPTION
**Pull request by pumano**
closes #98

### CODE REVIEW

**Comment by pumano** [comment]
@jannicz would love if you can check it.

**Comment by jannicz** [comment]
Thanks for the PR. Checking today...

**Comment by jannicz** [comment]
@pumano i prepared a release branch in my repository where i would like to merge your changes first. Could you change the merge target from jannicz:master to jannicz:RC-1.14 [here](https://github.com/jannicz/ng-svg-icon-sprite/tree/RC-1.14). I think there is something missing and i don't want to do the commit on your branch. Thank you very much for contributing!

**Comment by pumano** [comment]
@jannicz changed

**Comment by jannicz** [comment]
Thanks, now continuing on https://github.com/jannicz/ng-svg-icon-sprite/pull/102

**Pull request merged**
